version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/insightcare
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=insightcare
